### ISSUE TITLE
没看懂这一块是什么逻辑

### ISSUE THREAD

**Issue by paomian** [killme2008/clj-rate-limiter#2]
https://github.com/killme2008/clj-rate-limiter/blob/be50cf6d9f5c0d27824f4aba34c3067611d44b38/src/clj_rate_limiter/core.clj#L192-L196

**Comment by paomian** [comment]
ping

**Comment by killme2008** [comment]
什么逻辑？这里就是返回当前总的并发数.

**Comment by paomian** [comment]
但是 if 的两个分之里面，返回的内容是一样的，有必要做这个 if 判断么？

**Comment by killme2008** [comment]
@paomian 现在没有必要了。
